name: pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python 3.7 Iris 3.1.0
      # Pin all relevant versions to match common community installations
      run: |
        $CONDA/bin/conda install -c conda-forge python=3.7.12 iris=3.1.0 cf-units=3.0.1 cftime=1.5.1.1 netCDF4=1.5.8 libnetcdf=4.8.1 numpy=1.21.5 udunits requests mock pytest filelock dask=2022.2.0
      if: matrix.python-version == '3.7'
    - name: Install latest Iris for all other Python versions
      run: |
        $CONDA/bin/conda install -c conda-forge python=${{ matrix.python-version }} iris cftime netcdf4 pytest filelock requests
      if: matrix.python-version == '3.8' || matrix.python-version == '3.9' || matrix.python-version == '3.10'
    - name: Run tests
      run: |
        export PYTHONPATH=.
        export PATH=$CONDA/bin:$PATH
        pytest -vv